- name: Provision Etcd
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Include variables
      include_vars: all.yml
    - name: Launch configuration is present
      ec2_lc:
        name: Etcd {{ etcd_ami_id }}
        image_id: "{{ etcd_ami_id }}"
        instance_profile_name: KubeEtcd
        instance_type: t2.micro
        key_name: "{{ ec2_keypair }}"
        region: "{{ vpc_region }}"
        volumes:
          - { device_name: /dev/xvdf, volume_size: 10, volume_type: gp2 }
      register: lc_out
    - name: ASG is present
      ec2_asg:
        name: Etcd
        min_size: "{{ etcd.cluster_size }}"
        max_size: "{{ etcd.cluster_size }}"
        desired_capacity: "{{ etcd.cluster_size }}"
        launch_config_name: "{{ lc_out.name }}"
        region: "{{ vpc_region }}"
        vpc_zone_identifier: "{{ vpc_kubernetes_subnets | map(attribute='id') | list }}"
        load_balancers:
          - etcd
        tags:
          - role: etcd
          - os: coreos
          - KubernetesCluster: "{{ kubernetes.name }}"
