- name: Provision Addons
  hosts: localhost
  gather_facts: false
  vars:
  tasks:
    - name: Info message is shown
      debug: msg="You need to have a proper kubectl setup in your PATH"
    - name: Include variables
      include_vars: all.yml
    # kube-flannel
    - name: kube-flannel template is rendered
      template:
        src: kube-addons/kube-flannel.yml
        dest: /tmp/kube-flannel.yml
    - name: kube-flannel is deployed
      shell: kubectl apply -f /tmp/kube-flannel.yml
    - name: kube-flannel temporary file is removed
      file:
        path: /tmp/kube-flannel.yml
        state: absent
    # kube-dns
    - name: kube-dns template is rendered
      template:
        src: kube-addons/kube-dns.yml
        dest: /tmp/kube-dns.yml
    - name: kube-dns is deployed
      shell: kubectl apply -f /tmp/kube-dns.yml
    - name: kube-dns temporary file is removed
      file:
        path: /tmp/kube-dns.yml
        state: absent
    # heapster
    - name: heapster template is rendered
      template:
        src: kube-addons/heapster.yml
        dest: /tmp/heapster.yml
    - name: heapster is deployed
      shell: kubectl apply -f /tmp/heapster.yml
    - name: heapster temporary file is removed
      file:
        path: /tmp/heapster.yml
        state: absent
    # kube-dashboard
    - name: kube-dashboard template is rendered
      template:
        src: kube-addons/kube-dashboard.yml
        dest: /tmp/kube-dashboard.yml
    - name: kube-dashboard is deployed
      shell: kubectl apply -f /tmp/kube-dashboard.yml
    - name: kube-dashboard temporary file is removed
      file:
        path: /tmp/kube-dashboard.yml
        state: absent
