- name: Provision Master
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Include variables
      include_vars: all.yml
    - name: Launch configuration is present
      ec2_lc:
        name: KubeMaster {{ master_ami_id }}
        image_id: "{{ master_ami_id }}"
        instance_profile_name: KubeMaster
        instance_type: t2.micro
        key_name: "{{ ec2_keypair }}"
        region: "{{ vpc_region }}"
      register: lc_out
    - name: ASG is present
      ec2_asg:
        name: KubeMaster
        min_size: "{{ kubernetes.master_count }}"
        max_size: "{{ kubernetes.master_count }}"
        desired_capacity: "{{ kubernetes.master_count }}"
        launch_config_name: "{{ lc_out.name }}"
        region: "{{ vpc_region }}"
        vpc_zone_identifier: "{{ vpc_kubernetes_subnets | map(attribute='id') | list }}"
        load_balancers:
          - kubernetes
        tags:
          - role: master
          - os: coreos
          - KubernetesCluster: "{{ kubernetes.name }}"
