apiVersion: v1
kind: Config
clusters:
- name: default
  cluster:
    certificate-authority: /run/ssl/master/ca.pem
    server: "http://localhost:8080"
users:
- name: master
  user:
    client-certificate: /run/ssl/master/master.pem
    client-key: /run/ssl/master/master-key.pem
contexts:
- name: default-context
  context:
    cluster: default
    user: master
current-context: default-context
