apiVersion: v1
kind: Config
clusters:
- name: default
  cluster:
    certificate-authority: /run/ssl/worker/ca.pem
    server: "https://{{ kubernetes.endpoint }}:6443"
users:
- name: worker
  user:
    client-certificate: /run/ssl/worker/worker.pem
    client-key: /run/ssl/worker/worker-key.pem
contexts:
- name: default-context
  context:
    cluster: default
    user: worker
current-context: default-context
